---
  - name: Install NTP & ntpdate
    apt:
      name: 
        - ntpdate
        - ntp
      state: present
    notify:
      - force ntp update

  - name: Start the service
    service:
      name: ntp
      state: started
      enabled: yes
