---
  - name: Install nginx
    apt:
      pkg: nginx-light
      state: present

  - name: Create /srv/www/public
    file:
      path: /srv/www/public
      state: directory

  - name: Copy the nginx configuration file
    template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
    notify:
     - restart nginx

  - name: Create config files in conf.d
    template:
      src: conf.d/{{item}}.j2
      dest: /etc/nginx/conf.d/{{item}}
    with_items:
      - ssl.conf
      - php.conf
    notify:
      - restart nginx

  - name: Create virtual hosts in sites-available
    template:
      src: vhosts/{{item}}.j2
      dest: /etc/nginx/sites-available/{{item}}
    with_items: "{{nginx_vhosts}}"
    notify:
      - restart nginx

  - name: Link virutal hosts to sites-enabled
    file:
      src: /etc/nginx/sites-available/{{item}}
      dest: /etc/nginx/sites-enabled/{{item}}
      state: link
    with_items: "{{nginx_vhosts}}"
    notify:
      - restart nginx

  - name: Start the nginx service
    service: name=nginx state=started enabled=yes
