---
# See content of /usr/share/zoneinfo for list of available time zones
timezone: Etc/UTC

# 50 MB
mail_max_email_size: 51200000
# See http://serverfault.com/a/413535
mail_hide_users_ip: 1
# Set "mail_banned_attachments: []" if you do not want to ban attachments
mail_banned_attachments:
  - bat
  - com
  - exe
  - dll
  - vbs
# See http://ubuntuforums.org/showthread.php?t=493222
mail_log_tls_usage: 1

mail_db_name: mail
mail_db_host: 127.0.0.1
#mail_db_port: 3306 # Unused at the moment
mail_db_username: postfix

mailconsole_db_username: mailconsole


amavis_db_name: mail_amavis
amavis_db_host: 127.0.0.1
amavis_db_port: 3306
amavis_db_username: amavis


dovecot_db_username: dovecot


greylisting: 0
greylisting_db_name: mail_sqlgrey
greylisting_db_host: 127.0.0.1
greylisting_db_port: 3306
greylisting_db_username: sqlgrey
greylisting_web_username: admin


roundcube_version: 1.3.9
roundcube_db_name: mail_roundcube
roundcube_db_host: 127.0.0.1
roundcube_db_port: 3306
roundcube_db_username: roundcube

nginx_vhosts:
  - default.conf
  - mail_console.conf

mail_console_port: 10000

xmpp: 0
xmpp_db_name: mail_amavis
xmpp_db_host: localhost
xmpp_db_username: amavis
xmpp_domains:
  - "{{ hostname_domain }}"
