---
- hosts: all
  sudo: true
  vars_files:
    - settings.yml
  roles:
    - { role: common, tags: common }
    - { role: timezone, tags: timezone }
    - { role: unbound, tags: unbound }
    - { role: ntp, tags: ntp }
    - { role: mail, tags: mail }
    - { role: nginx, tags: nginx }
    - { role: roundcube, tags: roundcube }
