---
- hosts: all
  become: true
  vars_files:
    - settings.yaml
    - settings_local.yaml
  roles:
    - { role: selfsigned, tags: selfsigned }
    - { role: hostname, tags: hostname }
    - { role: timezone, tags: timezone }
    - { role: ntp, tags: ntp }
    - { role: unbound, tags: unbound }
    - { role: mail, tags: mail }
    - { role: nginx, tags: nginx }
    - { role: php, tags: php }
    - { role: mailconsole, tags: mailconsole }

#    - { role: roundcube, tags: roundcube }
#    - { role: sqlgrey_webui, tags: sqlgrey_webui, when: greylisting == 1 }
#    - { role: prosody, tags: prosody, when: xmpp == 1 }
