---
- hosts: all
  sudo: true
  vars_files:
    - settings.yml
  roles:
    - { role: common, tags: common }
    - { role: timezone, tags: timezone }
    - { role: ntp, tags: ntp }
    - { role: unbound, tags: unbound }
    - { role: nginx, tags: nginx }
    - { role: php, tags: php }
    - { role: mail, tags: mail }
    - { role: roundcube, tags: roundcube }
    - { role: sqlgrey_webui, tags: sqlgrey_webui, when: greylisting == 1 }
    - { role: prosody, tags: prosody, when: xmpp == 1 }
