---
  - name: Install Unbound
    apt:
      pkg: unbound
      state: present

  - name: Set resolv.conf to use localhost for DNS
    template:
      src: resolv.conf.j2
      dest: /etc/resolv.conf

  - name: Start the service
    service: 
      name: unbound
      state: started
      enabled: yes
