---
  - name: Install tzdata
    apt: name=tzdata state=present

  - name: Stat /usr/share/zoneinfo/{{ timezone }} 
    stat: path=/usr/share/zoneinfo/{{ timezone }}
    register: t_zone
  
  - name: Check if /usr/share/zoneinfo/{{ timezone }} exists
    fail: msg="{{ timezone }} is not a valid timezone"
    when: t_zone.stat.exists is not defined or t_zone.stat.exists == false
  
  - name: Set timezone to "{{timezone}}"
    timezone:
      name: "{{timezone}}"
